// Code generated by "stringer -type Op -trimprefix Op"; DO NOT EDIT.

package ir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpInvalid-0]
	_ = x[OpBad-1]
	_ = x[OpBreak-2]
	_ = x[OpContinue-3]
	_ = x[OpIf-4]
	_ = x[OpIfElse-5]
	_ = x[OpSwitch-6]
	_ = x[OpCase-7]
	_ = x[OpDefaultCase-8]
	_ = x[OpWhile-9]
	_ = x[OpDoWhile-10]
	_ = x[OpBlock-11]
	_ = x[OpReturn-12]
	_ = x[OpReturnVoid-13]
	_ = x[OpEcho-14]
	_ = x[OpParens-15]
	_ = x[OpAssign-16]
	_ = x[OpAssignModify-17]
	_ = x[OpBoolLit-18]
	_ = x[OpIntLit-19]
	_ = x[OpFloatLit-20]
	_ = x[OpStringLit-21]
	_ = x[OpInterpolatedString-22]
	_ = x[OpArrayLit-23]
	_ = x[OpVar-24]
	_ = x[OpName-25]
	_ = x[OpNew-26]
	_ = x[OpNot-27]
	_ = x[OpMemberAccess-28]
	_ = x[OpIndex-29]
	_ = x[OpNegation-30]
	_ = x[OpUnaryPlus-31]
	_ = x[OpConcat-32]
	_ = x[OpAdd-33]
	_ = x[OpSub-34]
	_ = x[OpDiv-35]
	_ = x[OpMul-36]
	_ = x[OpMod-37]
	_ = x[OpExp-38]
	_ = x[OpAnd-39]
	_ = x[OpAndWord-40]
	_ = x[OpOr-41]
	_ = x[OpOrWord-42]
	_ = x[OpXorWord-43]
	_ = x[OpTernary-44]
	_ = x[OpCall-45]
	_ = x[OpLess-46]
	_ = x[OpLessOrEqual-47]
	_ = x[OpGreater-48]
	_ = x[OpGreaterOrEqual-49]
	_ = x[OpEqual2-50]
	_ = x[OpFloatEqual2-51]
	_ = x[OpEqual3-52]
	_ = x[OpFloatEqual3-53]
	_ = x[OpNotEqual2-54]
	_ = x[OpNotFloatEqual2-55]
	_ = x[OpNotEqual3-56]
	_ = x[OpNotFloatEqual3-57]
	_ = x[OpSpaceship-58]
	_ = x[OpPostInc-59]
	_ = x[OpPreInc-60]
	_ = x[OpPostDec-61]
	_ = x[OpPreDec-62]
	_ = x[OpCast-63]
	_ = x[OpBitAnd-64]
	_ = x[OpBitOr-65]
	_ = x[OpBitXor-66]
	_ = x[OpBitNot-67]
	_ = x[OpBitShiftLeft-68]
	_ = x[OpBitShiftRight-69]
	_ = x[OpNullCoalesce-70]
}

const _Op_name = "InvalidBadBreakContinueIfIfElseSwitchCaseDefaultCaseWhileDoWhileBlockReturnReturnVoidEchoParensAssignAssignModifyBoolLitIntLitFloatLitStringLitInterpolatedStringArrayLitVarNameNewNotMemberAccessIndexNegationUnaryPlusConcatAddSubDivMulModExpAndAndWordOrOrWordXorWordTernaryCallLessLessOrEqualGreaterGreaterOrEqualEqual2FloatEqual2Equal3FloatEqual3NotEqual2NotFloatEqual2NotEqual3NotFloatEqual3SpaceshipPostIncPreIncPostDecPreDecCastBitAndBitOrBitXorBitNotBitShiftLeftBitShiftRightNullCoalesce"

var _Op_index = [...]uint16{0, 7, 10, 15, 23, 25, 31, 37, 41, 52, 57, 64, 69, 75, 85, 89, 95, 101, 113, 120, 126, 134, 143, 161, 169, 172, 176, 179, 182, 194, 199, 207, 216, 222, 225, 228, 231, 234, 237, 240, 243, 250, 252, 258, 265, 272, 276, 280, 291, 298, 312, 318, 329, 335, 346, 355, 369, 378, 392, 401, 408, 414, 421, 427, 431, 437, 442, 448, 454, 466, 479, 491}

func (i Op) String() string {
	if i < 0 || i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
