// Code generated by "stringer -type ScalarKind -trimprefix Scalar"; DO NOT EDIT.

package ir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ScalarUnknown-0]
	_ = x[ScalarVoid-1]
	_ = x[ScalarBool-2]
	_ = x[ScalarInt-3]
	_ = x[ScalarFloat-4]
	_ = x[ScalarString-5]
	_ = x[ScalarMixed-6]
}

const _ScalarKind_name = "UnknownVoidBoolIntFloatStringMixed"

var _ScalarKind_index = [...]uint8{0, 7, 11, 15, 18, 23, 29, 34}

func (i ScalarKind) String() string {
	if i < 0 || i >= ScalarKind(len(_ScalarKind_index)-1) {
		return "ScalarKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScalarKind_name[_ScalarKind_index[i]:_ScalarKind_index[i+1]]
}
